# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            TuxRiders
tagline:          'Project Site'
description:      ''
url:              http://www.tuxriders.com/

highlighter:      rouge
markdown:         kramdown

paginate:         5

github:
  repo:           https://github.com/TuxRiders/homepage
